[project]
name = "multi-choices-parser"
version = "0.9.61"
description = "An efficient incremental parser for multi-choices grammars."
readme = "README.md"
authors = [
    { name = "Hichem Ammar Khodja", email = "hichem5696@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
]

[project.urls]
Homepage = "https://github.com/HichemAK/multi-choices-parser"

[project.scripts]
multi-choices-parser = "multi_choices_parser:main"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pytest>=7.4.4",
]
