[project]
name = "multi-choices-parser"
version = "0.10.0"
description = "An efficient C++ incremental parser for multi-choices grammars (generalization of the trie structure) with Python bindings."
readme = "README.md"
authors = [
    { name = "Hichem Ammar Khodja", email = "hichem5696@gmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[project.urls]
Homepage = "https://github.com/HichemAK/multi-choices-parser"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"
sdist.exclude = [".github", "tests", "examples", ".gitignore", ".python-version"]

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = [
    "pytest",
    "numpy>=1.20.0",
    "pandas>=1.3.0",
    "matplotlib>=3.4.0",
    "scipy>=1.7.0",
]
